include("display.jl")
println("==== compare regular and tensor mesh ====")
include("regularVStensor.jl")
println("==== test differential operators ====")
include("testDiffOps.jl")
include("testInterpolationMatrix.jl")
println("==== test differential operators ====")
include("testAvgOps.jl")
println("==== test persistency of linear operators ====")
include("testBoundaryNodes.jl")
println("==== test boundary and inner node indices ====")
include("testPersistency.jl")
println(" Mesh: All tests passed!")
